services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.${NODE_ENV:-dev}
    container_name: api
    restart: unless-stopped
    ports:
      - '${API_HTTP_PORT:-7400}:${API_HTTP_PORT:-7400}'
    env_file:
      - .env.${NODE_ENV:-dev}
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
    depends_on:
      - migrations
      - db

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.${NODE_ENV:-dev}
    container_name: migrations
    command: yarn typeorm migration:run -d src/config/orm.datasource.ts
    env_file:
      - .env.${NODE_ENV:-dev}
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: auto-access-system-db
    restart: unless-stopped
    ports:
      - '${DB_PORT:-5432}:5432'
    env_file:
      - .env.${NODE_ENV:-dev}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
