# Используем официальный образ Node.js
FROM node:20-alpine

# Создаем директорию приложения
WORKDIR /usr/app

# Копируем package.json и yarn.lock
COPY package.json yarn.lock ./

# Устанавливаем зависимости
RUN yarn install

# Копируем исходный код
COPY . .

# Собираем приложение
RUN yarn build

# Открываем порт
EXPOSE ${API_HTTP_PORT}

# Запускаем приложение
CMD ["yarn", "start:prod"] 